-- PAS CHER
CREATE OR ALTER VIEW ACTIVITES_MODIQUES AS

SELECT ACTIVITE.IDSTATION, STATION.nomStation, ACTIVITE.LIBELLE, ACTIVITE.PRIX FROM ACTIVITE 

JOIN STATION ON STATION.ID = ACTIVITE.idStation

WHERE ACTIVITE.PRIX < 140



-- Appel de la view
SELECT * FROM ACTIVITES_MODIQUES;




-- CHER
CREATE OR ALTER VIEW ACTIVITES_CHERES AS

SELECT ACTIVITE.IDSTATION, STATION.nomStation, ACTIVITE.LIBELLE, ACTIVITE.PRIX FROM ACTIVITE 

JOIN STATION ON STATION.ID = ACTIVITE.idStation

WHERE ACTIVITE.PRIX > 140


-- Appel de la view
SELECT * FROM ACTIVITES_CHERES;




-- CONVERSION TARIF EURO
CREATE OR ALTER VIEW STATIONEURO AS

SELECT STATION.nomStation, STATION.capacite, STATION.lieu, ROUND(STATION.tarif / 6.58, 2) AS TARIF_EURO FROM STATION 


-- Appel de la view
SELECT * FROM STATIONEURO;






-- TARIF ET PRIX MIN MAX
CREATE OR ALTER VIEW TARIFS AS 

SELECT STATION.nomStation, STATION.tarif, MIN(ACTIVITE.PRIX) AS OPTIONMIN, MAX(ACTIVITE.PRIX) AS OPTIONMAX FROM STATION

JOIN ACTIVITE ON ACTIVITE.IDSTATION = STATION.id
GROUP BY STATION.nomStation, STATION.tarif;

-- Appel de la view
SELECT * FROM TARIFS;